---
- name: Install the latest versions
  yum:
    name:
      - python3-psycopg2
    state: latest

- name: "Install packages" 
  dnf: "name={{ item }} state=present"
  with_items:
    - postgresql
    - postgresql-server

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "{{db_location}}pg_hba.conf"
  register: postgres_data

- name: Replicate db
  command: pg_basebackup -P -R -h {{main_ip}} -U {{main_user}} -D ~/data/
  become_user: postgres

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql